// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3UiNnf4qkm5bzAqogxGYw--G2927bEFg',
    appId: '1:572239598950:web:fad2b6ef32426c47bae4a7',
    messagingSenderId: '572239598950',
    projectId: 'fitnessapp-361b4',
    authDomain: 'fitnessapp-361b4.firebaseapp.com',
    storageBucket: 'fitnessapp-361b4.firebasestorage.app',
    measurementId: 'G-0ZD8HB7FMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6-xQF5ymQo5QnGe76P7sCoMro1Sdr5Y',
    appId: '1:572239598950:android:57aa1b70472b5480bae4a7',
    messagingSenderId: '572239598950',
    projectId: 'fitnessapp-361b4',
    storageBucket: 'fitnessapp-361b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZX0qaZnAlHBFNypjTZkqmmMClpsJTsU',
    appId: '1:572239598950:ios:5b85f5013576e5a4bae4a7',
    messagingSenderId: '572239598950',
    projectId: 'fitnessapp-361b4',
    storageBucket: 'fitnessapp-361b4.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ZX0qaZnAlHBFNypjTZkqmmMClpsJTsU',
    appId: '1:572239598950:ios:5b85f5013576e5a4bae4a7',
    messagingSenderId: '572239598950',
    projectId: 'fitnessapp-361b4',
    storageBucket: 'fitnessapp-361b4.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );
}
